### ISSUE TITLE
error: there are multiple default operator classes for data type text

### ISSUE THREAD

**Issue by Kvariani** [michaelsogos/pg-diff#16] opened 2020-03-19 16:36 UTC
[||||||-------------] 33% - Collecting PRIVILEGES for table "public"."schedulegeneratorschedulegeneratorscollection_heal[||||||-------------] 33% - Collecting PRIVILEGES for table "public"."agroinsuranceaccident"
error: there are multiple default operator classes for data type text
error: there are multiple default operator classes for data type text
    at Connection.parseE (C:\Users\bkvariani\AppData\Roaming\npm\node_modules\pg-diff-cli\node_modules\pg\lib\connection.js:614:13)
    at Connection.parseMessage (C:\Users\bkvariani\AppData\Roaming\npm\node_modules\pg-diff-cli\node_modules\pg\lib\connection.js:413:19)
    at Socket.<anonymous> (C:\Users\bkvariani\AppData\Roaming\npm\node_modules\pg-diff-cli\node_modules\pg\lib\connection.js:129:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

![image](https://user-images.githubusercontent.com/16977005/77091279-c9c7c900-6a21-11ea-8a01-465487605441.png)

**Comment by Kvariani** [comment] 2020-03-19 16:36
@petrechitashvili

**Comment by michaelsogos** [comment] 2020-05-09 14:17
Hi @Kvariani ,

I need more details.
Can you please give me DDL of the table "agroinsuranceaccident"?
You can use DBEaver to get it.

**Comment by michaelsogos** [comment] 2020-05-26 05:13
Hi @Kvariani,

Is this still a problem?
Can you supply the create table script in order to debug the issue?

**Comment by michaelsogos** [comment] 2021-01-24 11:53
@Kvariani 

For now i will close it because i cannot reproduce the bug, if you can answer to the above question than i will investigate.

**Closed as completed by michaelsogos** 2021-01-24 11:53 UTC
Labels: question, not replicable
