### ISSUE TITLE
Functions are always shown as different even when not updated

### ISSUE THREAD

**Issue by JonathonCwik** [michaelsogos/pg-diff#27] opened 2020-05-29 15:15 UTC
PostgreSQL Version: 12.2 (I upgraded both sides to make sure that the issue wasn't mismatched versions)

Example:

The diff gives me this function:
```
CREATE OR REPLACE FUNCTION public.get_browser_from_user_agent(user_agent text)
 RETURNS text
 LANGUAGE sql
 PARALLEL SAFE
AS $function$
	 SELECT CASE
        WHEN user_agent LIKE '%Firefox/%' THEN 'Firefox'
        WHEN user_agent LIKE '%Chrome/%' OR user_agent LIKE '%CriOS%' THEN 'Chrome'
        WHEN user_agent LIKE '%MSIE %' THEN 'IE'
        WHEN user_agent LIKE '%MSIE+%' THEN 'IE'
        WHEN user_agent LIKE '%Trident%' THEN 'IE'
        WHEN user_agent LIKE '%iPhone%' THEN 'iPhone Safari'
        WHEN user_agent LIKE '%iPad%' THEN 'iPad Safari'
        WHEN user_agent LIKE '%Opera%' THEN 'Opera'
        WHEN user_agent LIKE '%BlackBerry%' AND user_agent LIKE '%Version/%' THEN 'BlackBerry WebKit'
        WHEN user_agent LIKE '%BlackBerry%' THEN 'BlackBerry'
        WHEN user_agent LIKE '%Android%' THEN 'Android'
        WHEN user_agent LIKE '%Safari%' THEN 'Safari'
        WHEN user_agent LIKE '%bot%' THEN 'Bot'
        WHEN user_agent LIKE '%http://%' THEN 'Bot'
        WHEN user_agent LIKE '%www.%' THEN 'Bot'
        WHEN user_agent LIKE '%Wget%' THEN 'Bot'
        WHEN user_agent LIKE '%curl%' THEN 'Bot'
        WHEN user_agent LIKE '%urllib%' THEN 'Bot'
        ELSE 'Unknown'
      END
$function$
;
ALTER FUNCTION "public"."get_browser_from_user_agent"(text) OWNER TO ----------;
```

After I run it, it still shows up in the diff exactly as if it was never ran.

**Comment by michaelsogos** [comment] 2020-05-29 21:49
Dear @JonathonCwik ,

The issue is fixed on v2.0.3
Thanks for the issue.

Finally your problem was related to the \r (aka char(10)) that in different PGSQL configuration can be ommited once you create a new FUNCTION, VIEW or MVIEW.
In my dev environment \r are always "skipped" anywhere to be compatible wherever i work on windows or unix machine 😄, that's why i didn't notice that.

WARNING:
I fixed also other bugs (inattentive bug) like the option -mt and -ms were inverted, so pay attention that now -mt work properly 😞.

**Closed as completed by michaelsogos** 2020-05-29 21:49 UTC
Labels: bug
