### ISSUE TITLE
Column Does not Exist

### ISSUE THREAD

**Issue by rosscoombes** [michaelsogos/pg-diff#41] opened 2021-08-09 20:29 UTC
On the face of it, this seems similar to #24.  The last status output was "AGGREGATE objects have been compared. at 75%

At this point though, as it's not telling me the table so I've not yet understood which  property or function it has an issue with (there's quite a few referencing nodeid).
#24 says this is fixed in 2.0.2, I'm using...

Version: 2.3.1
PostgreSQL: 9.6+

Full error message is...

error: column "nodeid" does not exist
    at Parser.parseErrorMessage (node_modules\pg-diff-cli\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (node_modules\pg-diff-cli\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (node_modules\pg-diff-cli\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (node_modules\pg-diff-cli\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
column "nodeid" does not exist

Anyone know what to look for or how to find out which table its referring to?

Thank you.

**Comment by rosscoombes** [comment] 2021-08-09 20:40
Just wrote out the buffer to the console and found a bit more information...

column "nodeid" does not exist. Perhaps you meant to reference the column "Collectables.nodeId"

As the above suggests, the table in question has nodeId as a column but not nodeid lowercase.  Is it possible somewhere in the data comparison section that the column is not being wrapped in quotes in order to preserve the camel case?

**Comment by michaelsogos** [comment] 2021-08-09 21:17
Dear @rosscoombes 

Of course it can be, and of course it is a bug because pg-diff as well tested for any name case (pascal and camel too).
So it must work, no option 😄 .

To help me address the issue could you supply just table schema? I will fullfil with dummy data my own.

**Comment by michaelsogos** [comment] 2021-08-09 21:22
Anyway @rosscoombes 

The error is not mine, it comes from PG.
Also it is not related to AGGREGATE because once i print out a sentence means that a step has been gone. Said that AGGREGATE FUNCTION is last thing done for SCHEMA COMPARSION, so your error is on DATA COMPARE, that it should mean two possible things:
* I found two table (on source and on target db) which have different schema (but i should prevent this from begining)
* OR -- i'm not quoting object names, as you suggest

**Comment by rosscoombes** [comment] 2021-08-10 10:38
Hi Michael,

Thanks for the quick response (much earlier than I expected).

OK, so this is the table schema I believe its complaining about...

"dataCompare": {
   "enable": true,
  "tables": [{
     "tableName": "Collectables",
     "tableSchema": "public",
     "tableKeyFields": [
       "id",
       "nodeId",
       "expires",
       "respawn",
       "value",
       "createdAt",
       "updatedAt"
      ]
}

To test whether my objects not being quoted theory was right, I concluded that if I were to remove nodeId from the above, it would presumably error when it got to createdAt as the next column that uses camel case.

Sure enough, it does.

So.... I went digging and I believe I have found the problem.

CompareApi.js -> collectTableRecords - sorry I don't have the exact line number now but approx 1220, the line is this one...

let response = await client.query(
                        `SELECT MD5(ROW(${tableDefinition.tableKeyFields.join(",")})::text) AS "rowHash", * FROM ${fullTableName}`);

This is making an MD5 hash out of the column names without the quoting.  I changed the above to map the additional quotations in before the .join and the script successfully continues past.  

i.e.

let response = await client.query(
                        `SELECT MD5(ROW(${tableDefinition.tableKeyFields.map((x) => `"${x}"`).join(",")})::text) AS "rowHash", * FROM ${fullTableName}`


At the moment I then do hit another error but I believe this is complaining about a virtual column so outside the scope of this.

Hope that helps.

**Comment by rosscoombes** [comment] 2021-08-10 11:03
Never done a pull request before but just submitted what I believe is correct.

**Comment by michaelsogos** [comment] 2021-08-10 12:09
Dear @rosscoombes 

Great help yours!
But i'm asking the CREATE TABLE sql statement (you can retrieve easily from pgAdmin or DBeaver, or any GUI tool you like to connect to PGSQL); i need it to add it on my unit test and also i'd like to test for virtual column in order to resolve that bug too.

In the mean time i will do my best to reproduce the issue with info you gave me, but it will better with CREATE TABLE in hand.

**Comment by michaelsogos** [comment] 2021-08-10 15:02
Dear @rosscoombes 

Fixed on v2.4.0.
Can you give a try and let me know in case of error?

**Closed as completed by michaelsogos** 2021-08-10 15:02 UTC
Labels: bug, question

**Comment by rosscoombes** [comment] 2021-08-11 08:17
Yep, all looks good.  Thank you.

Just hit a new problem, this one could well be me but I'll raise a new issue.
